In [6]:
import torch

#Create  a simple tensor
x = torch.tensor([[1,2], [3, 4]], dtype= torch.float32)
print(x)

#some basic operation 

print(x+x)
print(x*2)
print(x.device)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
cpu
